repositories:
  - name: helloworld-repo
    url: git+https://github.com/isirfanm/complete-helm-chart-tutorial@helloworld
releases:
  - name: helloworld
    chart: helloworld-repo/helloworld
    installed: true 